# Generated by Django 4.2.4 on 2023-08-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(upload_to="events/"),
        ),
    ]
