import datetime
AWS_ACCESS_KEY_ID = "AKIAWFNY7OE3QBQSXJSX"
AWS_SECRET_ACCESS_KEY = "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"
AWS_FILE_EXPIRE = 200
AWS_PRELOAD_METADATA = True
AWS_QUERYSTRING_AUTH = True
AWS_DEFAULT_ACL = None
AWS_S3_ADDRESSING_STYLE = "virtual"

DEFAULT_FILE_STORAGE = 'Eventz.aws.utils.MediaRootS3BotoStorage'
STATICFILES_STORAGE = 'Eventz.aws.utils.StaticRootS3BotoStorage'
AWS_STORAGE_BUCKET_NAME = 'my-events-bucket'

AWS_S3_REGION_NAME = "ap-south-1"
AWS_S3_SIGNATURE_VERSION = "s3v4"